# Generated by Django 4.1.3 on 2023-04-29 09:07

from django.db import migrations, models
import registerApp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('medications', models.CharField(max_length=400)),
                ('gender', models.CharField(max_length=100)),
                ('medical_history', models.CharField(max_length=400)),
                ('allergies', models.CharField(max_length=400)),
                ('first_contact_name', models.CharField(max_length=100)),
                ('first_contact_number', models.CharField(max_length=8)),
                ('vaccines', models.CharField(max_length=400)),
                ('image', models.ImageField(upload_to=registerApp.models.CustomStorage.custom_upload_to)),
            ],
        ),
    ]
